apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - port: 3000           # The port your app listens on inside the pod
      targetPort: 3000     # The container port
      nodePort: 30080      # The external port (range: 30000–32767)
