apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gitops-app
  namespace: default
spec:
  interval: 1m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-sample-app
  targetNamespace: default