name: Build and Push docker Image

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      githubUsername: ${{ github.repository_owner.toLowerCase() }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug token
        run: echo "GITHUB_TOKEN is available"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image with docker
        working-directory: ./
        run: |
          IMAGE=ghcr.io/${{ githubUsername }}/gitops-sample-app:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Update Kubernetes manifest with new image tag
        run: |
          IMAGE=ghcr.io/${{ githubUsername }}/gitops-sample-app:latest
          sed -i "s|image:.*|image: $IMAGE_LOWER|" k8s/deployment.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag [skip ci]" || echo "No changes"
          git push
